production: &defaults
  host: localhost
  adapter: postgresql
  encoding: unicode
  database: mops_new_production
  pool: 5
  username: enbake
  password: enbake

development:
  <<: *defaults
  database: mops_new_development

test:
  <<: *defaults
  database: mops_new_test
